import { type NextPage } from "next";
import Head from "next/head";

import Layout from "@layouts/navigation/Layout";
import Daily from "@components/daily/Daily";
import { useEffect, useState } from "react";

const FoodPage: NextPage = () => {
    const [foods, setFoods] = useState([]);
    const [pages, setPages] = useState(0);
    const [page, setPage] = useState(1);
    const [total, setTotal] = useState(0);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        const url = `https://api.nal.usda.gov/fdc/v1/search`
        const query = {
            params: {
                api_key: apiKey,
                generalSearchInput: search,
                dataType: 'Branded',
                pageNumber: page,
                pageSize: 10,
            }
        }

        setLoading(true);
        axios.get(url, query)
            .then(res => {
                setFoods(res.data.foods);
                setPages(res.data.totalPages);
                setTotal(res.data.totalHits);
                setLoading(false);
            })
            .catch(err => {
                console.log(err);
            })
    }, [search, page]);
    
    return (
        <>
            <Head>
                <title>Calorie Counter - Food</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                {loading ?
                    <Loading /> :
                    <FoodList items={foods} />
                }
            </Layout>
        </>
    );
};

export default FoodPage;